package com.bloom;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BloomMod implements ModInitializer {
   public static final String MOD_ID = "vybrantvisual";
   public static final Logger LOGGER = LoggerFactory.getLogger("vybrantvisual");
   private static final float BIRD_CALL_RANGE = 128.0F;
   private static final float GEESE_FLOCK_CALL_RANGE = 256.0F;
   public static final Identifier FOG_FX_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "fog_fx");
   public static final SimpleParticleType FOG_FX_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier MIST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "mist");
   public static final SimpleParticleType MIST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier GROUND_MIST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "ground_mist");
   public static final SimpleParticleType GROUND_MIST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier DESERT_DUST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "desert_dust");
   public static final SimpleParticleType DESERT_DUST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier NETHER_RAYS_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "nether_rays");
   public static final SimpleParticleType NETHER_RAYS_PARTICLE = FabricParticleTypes.simple(true);
   public static final Identifier LAVA_STEAM_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_steam");
   public static final SimpleParticleType LAVA_STEAM_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_EMBER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_ember");
   public static final SimpleParticleType LAVA_EMBER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_POP_BIG_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_big");
   public static final SimpleParticleType LAVA_POP_BIG_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_POP_SMALL_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_small");
   public static final SimpleParticleType LAVA_POP_SMALL_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_POP_SNAPPY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_snappy");
   public static final SimpleParticleType LAVA_POP_SNAPPY_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_SPRAY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_spray");
   public static final SimpleParticleType LAVA_SPRAY_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_SPRAY_FLASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_spray_flash");
   public static final SimpleParticleType LAVA_SPRAY_FLASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_DROPLET_SPLASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_droplet_splash");
   public static final SimpleParticleType LAVA_DROPLET_SPLASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier GLOWING_ASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "glowing_ash");
   public static final SimpleParticleType GLOWING_ASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier CUSTOM_RAIN_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "custom_rain");
   public static final SimpleParticleType CUSTOM_RAIN_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BLOCK_SIDE_RAIN_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "block_side_rain");
   public static final SimpleParticleType BLOCK_SIDE_RAIN_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier CUSTOM_RAIN_SPLASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "custom_rain_splash");
   public static final SimpleParticleType CUSTOM_RAIN_SPLASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier RAIN_PUDDLE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "rain_puddle");
   public static final SimpleParticleType RAIN_PUDDLE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BOAT_SPLASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "boat_splash");
   public static final SimpleParticleType BOAT_SPLASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BOAT_TRAIL_FOAM_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "boat_trail_foam");
   public static final SimpleParticleType BOAT_TRAIL_FOAM_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BOAT_TRAIL_WAKE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "boat_trail_wake");
   public static final SimpleParticleType BOAT_TRAIL_WAKE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier UNDERWATER_CHEST_BUBBLE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "underwater_chest_bubble");
   public static final SimpleParticleType UNDERWATER_CHEST_BUBBLE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier UNDERWATER_ENDER_CHEST_BUBBLE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "underwater_ender_chest_bubble");
   public static final SimpleParticleType UNDERWATER_ENDER_CHEST_BUBBLE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TRAILER_SPLASH_OUTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "trailer_splash_outer");
   public static final SimpleParticleType TRAILER_SPLASH_OUTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TRAILER_SPLASH_MIDDLE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "trailer_splash_middle");
   public static final SimpleParticleType TRAILER_SPLASH_MIDDLE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TRAILER_SPLASH_LOW_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "trailer_splash_low");
   public static final SimpleParticleType TRAILER_SPLASH_LOW_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TRAILER_SPLASH_BAND_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "trailer_splash_band");
   public static final SimpleParticleType TRAILER_SPLASH_BAND_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WATER_SPLASH_DROPLET_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "water_splash_droplet");
   public static final SimpleParticleType WATER_SPLASH_DROPLET_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WATER_CASCADE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "water_cascade");
   public static final SimpleParticleType WATER_CASCADE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WEATHER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "weather_particle");
   public static final SimpleParticleType WEATHER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier CAVE_DUST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "cave_dust");
   public static final SimpleParticleType CAVE_DUST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier AMETHYST_SPARKLE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "amethyst_sparkle");
   public static final SimpleParticleType AMETHYST_SPARKLE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LANTERN_MOTE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lantern_mote");
   public static final SimpleParticleType LANTERN_MOTE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier SOUL_LANTERN_MOTE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "soul_lantern_mote");
   public static final SimpleParticleType SOUL_LANTERN_MOTE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier COPPER_LANTERN_MOTE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "copper_lantern_mote");
   public static final SimpleParticleType COPPER_LANTERN_MOTE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TORCH_SPARK_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "torch_spark");
   public static final SimpleParticleType TORCH_SPARK_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier SOUL_TORCH_SPARK_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "soul_torch_spark");
   public static final SimpleParticleType SOUL_TORCH_SPARK_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier COPPER_TORCH_SPARK_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "copper_torch_spark");
   public static final SimpleParticleType COPPER_TORCH_SPARK_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier TORCH_SMOKE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "torch_smoke");
   public static final SimpleParticleType TORCH_SMOKE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier JELLYFISH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "jellyfish");
   public static final SimpleParticleType JELLYFISH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier END_PORTAL_EYE_PLACEMENT_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "end_portal_eye_placement");
   public static final SimpleParticleType END_PORTAL_EYE_PLACEMENT_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_LIGHT_RAY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_light_ray");
   public static final SimpleParticleType WORLD_AMBIENCE_LIGHT_RAY_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_DISTANT_LIGHT_RAY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_distant_light_ray");
   public static final SimpleParticleType WORLD_AMBIENCE_DISTANT_LIGHT_RAY_PARTICLE = FabricParticleTypes.simple(true);
   public static final Identifier WORLD_AMBIENCE_LENS_FLARE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_lens_flare");
   public static final SimpleParticleType WORLD_AMBIENCE_LENS_FLARE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_WIND_GUST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_wind_gust");
   public static final SimpleParticleType WORLD_AMBIENCE_WIND_GUST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FIREFLY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_firefly");
   public static final SimpleParticleType WORLD_AMBIENCE_FIREFLY_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_POLLEN_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_pollen");
   public static final SimpleParticleType WORLD_AMBIENCE_POLLEN_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_WATER_POLLEN_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_water_pollen");
   public static final SimpleParticleType WORLD_AMBIENCE_WATER_POLLEN_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_BIRD_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_bird");
   public static final SimpleParticleType WORLD_AMBIENCE_BIRD_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_BUTTERFLY_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_butterfly");
   public static final SimpleParticleType WORLD_AMBIENCE_BUTTERFLY_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_GOOSE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_goose");
   public static final SimpleParticleType WORLD_AMBIENCE_GOOSE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_TUMBLEWEED_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_tumbleweed");
   public static final SimpleParticleType WORLD_AMBIENCE_TUMBLEWEED_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_CHERRY_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_cherry_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_CHERRY_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_PALE_OAK_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_pale_oak_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_PALE_OAK_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_SPRUCE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_spruce_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_SPRUCE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_BIRCH_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_birch_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_BIRCH_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_JUNGLE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_jungle_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_JUNGLE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_ACACIA_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_acacia_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_ACACIA_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_MANGROVE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_mangrove_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_MANGROVE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_PASSIVE_AZALEA_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_passive_azalea_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_PASSIVE_AZALEA_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_LEAF_GUST_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_leaf_gust");
   public static final SimpleParticleType WORLD_AMBIENCE_LEAF_GUST_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_CHERRY_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_cherry_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_CHERRY_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_CHORUS_PETAL_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_chorus_petal");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_CHORUS_PETAL_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_PALE_OAK_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_pale_oak_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_PALE_OAK_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_TINTED_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_tinted_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_TINTED_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_SPRUCE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_spruce_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_SPRUCE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_BIRCH_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_birch_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_BIRCH_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_JUNGLE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_jungle_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_JUNGLE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_ACACIA_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_acacia_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_ACACIA_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_MANGROVE_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_mangrove_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_MANGROVE_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_FALLING_AZALEA_LEAF_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_falling_azalea_leaf");
   public static final SimpleParticleType WORLD_AMBIENCE_FALLING_AZALEA_LEAF_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier WORLD_AMBIENCE_LEAF_WATER_SPLASH_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "world_ambience_leaf_water_splash");
   public static final SimpleParticleType WORLD_AMBIENCE_LEAF_WATER_SPLASH_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LEAF_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter");
   public static final SimpleParticleType LEAF_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LEAF_LITTER_KICKUP_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_kickup");
   public static final SimpleParticleType LEAF_LITTER_KICKUP_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier FLOWER_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "flower_litter");
   public static final SimpleParticleType FLOWER_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier PETAL_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "petal_litter");
   public static final SimpleParticleType PETAL_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BRANCH_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "branch_litter");
   public static final SimpleParticleType BRANCH_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier PEBBLE_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "pebble_litter");
   public static final SimpleParticleType PEBBLE_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier BEACH_PEBBLE_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "beach_pebble_litter");
   public static final SimpleParticleType BEACH_PEBBLE_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier SHELL_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "shell_litter");
   public static final SimpleParticleType SHELL_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LILY_PAD_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lily_pad_litter");
   public static final SimpleParticleType LILY_PAD_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LAVA_PLATE_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_plate");
   public static final SimpleParticleType LAVA_PLATE_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier DUCKWEED_LITTER_PARTICLE_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "duckweed_litter");
   public static final SimpleParticleType DUCKWEED_LITTER_PARTICLE = FabricParticleTypes.simple(false);
   public static final Identifier LEAF_LITTER_CONTACT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_contact");
   public static final SoundEvent LEAF_LITTER_CONTACT_SOUND;
   public static final Identifier LEAF_LITTER_WALK_SOUND_ID;
   public static final SoundEvent LEAF_LITTER_WALK_SOUND;
   public static final Identifier LEAF_LITTER_RUSTLE_SOUND_ID;
   public static final SoundEvent LEAF_LITTER_RUSTLE_SOUND;
   public static final Identifier LEAF_LITTER_SLIDE_SOUND_ID;
   public static final SoundEvent LEAF_LITTER_SLIDE_SOUND;
   public static final Identifier LEAF_LITTER_LAND_SOUND_ID;
   public static final SoundEvent LEAF_LITTER_LAND_SOUND;
   public static final Identifier TUMBLEWEED_HIT_01_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_HIT_01_SOUND;
   public static final Identifier TUMBLEWEED_HIT_02_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_HIT_02_SOUND;
   public static final Identifier TUMBLEWEED_HIT_03_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_HIT_03_SOUND;
   public static final Identifier TUMBLEWEED_HIT_04_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_HIT_04_SOUND;
   public static final Identifier TUMBLEWEED_PUNCH_01_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_PUNCH_01_SOUND;
   public static final Identifier TUMBLEWEED_PUNCH_02_SOUND_ID;
   public static final SoundEvent TUMBLEWEED_PUNCH_02_SOUND;
   public static final Identifier LAVA_POP_01_SOUND_ID;
   public static final SoundEvent LAVA_POP_01_SOUND;
   public static final Identifier LAVA_POP_02_SOUND_ID;
   public static final SoundEvent LAVA_POP_02_SOUND;
   public static final Identifier LAVA_POP_03_SOUND_ID;
   public static final SoundEvent LAVA_POP_03_SOUND;
   public static final Identifier LAVA_SPRAY_01_SOUND_ID;
   public static final SoundEvent LAVA_SPRAY_01_SOUND;
   public static final Identifier LAVA_SPRAY_02_SOUND_ID;
   public static final SoundEvent LAVA_SPRAY_02_SOUND;
   public static final Identifier LAVA_DROPLET_01_SOUND_ID;
   public static final SoundEvent LAVA_DROPLET_01_SOUND;
   public static final Identifier LAVA_DROPLET_02_SOUND_ID;
   public static final SoundEvent LAVA_DROPLET_02_SOUND;
   public static final Identifier FALLING_LEAF_WATER_SOUND_ID;
   public static final SoundEvent FALLING_LEAF_WATER_SOUND;
   public static final Identifier WATER_CASCADE_LOOP_SOUND_ID;
   public static final SoundEvent WATER_CASCADE_LOOP_SOUND;
   public static final Identifier BRANCH_LITTER_CONTACT_SOUND_ID;
   public static final SoundEvent BRANCH_LITTER_CONTACT_SOUND;
   public static final Identifier PEBBLE_LITTER_CONTACT_SOUND_ID;
   public static final SoundEvent PEBBLE_LITTER_CONTACT_SOUND;
   public static final Identifier WEATHER_DRIZZLE_SOUND_ID;
   public static final SoundEvent WEATHER_DRIZZLE_SOUND;
   public static final Identifier WEATHER_LIGHT_RAIN_SOUND_ID;
   public static final SoundEvent WEATHER_LIGHT_RAIN_SOUND;
   public static final Identifier WEATHER_DESERT_WIND_SOUND_ID;
   public static final SoundEvent WEATHER_DESERT_WIND_SOUND;
   public static final Identifier WEATHER_NETHER_STORM_SOUND_ID;
   public static final SoundEvent WEATHER_NETHER_STORM_SOUND;
   public static final Identifier PSYCHEDELIC_HALLUCINATION_SOUND_ID;
   public static final SoundEvent PSYCHEDELIC_HALLUCINATION_SOUND;
   public static final Identifier FIREFLY_BUSH_AMBIENT_SOUND_ID;
   public static final SoundEvent FIREFLY_BUSH_AMBIENT_SOUND;
   public static final Identifier CICADA_AMBIENT_SOUND_ID;
   public static final SoundEvent CICADA_AMBIENT_SOUND;
   public static final Identifier DEEP_DARK_AMBIENT_SOUND_ID;
   public static final SoundEvent DEEP_DARK_AMBIENT_SOUND;
   public static final Identifier BIRD_CONTINUOUS_SOUND_ID;
   public static final SoundEvent BIRD_CONTINUOUS_SOUND;
   public static final Identifier BIRD_CALL_01_SOUND_ID;
   public static final SoundEvent BIRD_CALL_01_SOUND;
   public static final Identifier BIRD_CALL_02_SOUND_ID;
   public static final SoundEvent BIRD_CALL_02_SOUND;
   public static final Identifier BIRD_CALL_03_SOUND_ID;
   public static final SoundEvent BIRD_CALL_03_SOUND;
   public static final Identifier BIRD_CALL_04_SOUND_ID;
   public static final SoundEvent BIRD_CALL_04_SOUND;
   public static final Identifier BIRD_CALL_05_SOUND_ID;
   public static final SoundEvent BIRD_CALL_05_SOUND;
   public static final Identifier BIRD_CALL_06_SOUND_ID;
   public static final SoundEvent BIRD_CALL_06_SOUND;
   public static final Identifier BIRD_CALL_07_SOUND_ID;
   public static final SoundEvent BIRD_CALL_07_SOUND;
   public static final Identifier BIRD_FLYAWAY_SOUND_ID;
   public static final SoundEvent BIRD_FLYAWAY_SOUND;
   public static final Identifier GEESE_CONTINUOUS_SOUND_ID;
   public static final SoundEvent GEESE_CONTINUOUS_SOUND;
   public static final Identifier GEESE_FLOCK_CALL_01_SOUND_ID;
   public static final SoundEvent GEESE_FLOCK_CALL_01_SOUND;
   public static final Identifier GEESE_FLOCK_CALL_02_SOUND_ID;
   public static final SoundEvent GEESE_FLOCK_CALL_02_SOUND;
   public static final Identifier GEESE_FLOCK_CALL_03_SOUND_ID;
   public static final SoundEvent GEESE_FLOCK_CALL_03_SOUND;

   public void onInitialize() {
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, FOG_FX_PARTICLE_ID, FOG_FX_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, MIST_PARTICLE_ID, MIST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, GROUND_MIST_PARTICLE_ID, GROUND_MIST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, DESERT_DUST_PARTICLE_ID, DESERT_DUST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, NETHER_RAYS_PARTICLE_ID, NETHER_RAYS_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_STEAM_PARTICLE_ID, LAVA_STEAM_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_EMBER_PARTICLE_ID, LAVA_EMBER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_POP_BIG_PARTICLE_ID, LAVA_POP_BIG_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_POP_SMALL_PARTICLE_ID, LAVA_POP_SMALL_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_POP_SNAPPY_PARTICLE_ID, LAVA_POP_SNAPPY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_SPRAY_PARTICLE_ID, LAVA_SPRAY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_SPRAY_FLASH_PARTICLE_ID, LAVA_SPRAY_FLASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_DROPLET_SPLASH_PARTICLE_ID, LAVA_DROPLET_SPLASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, GLOWING_ASH_PARTICLE_ID, GLOWING_ASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, CUSTOM_RAIN_PARTICLE_ID, CUSTOM_RAIN_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BLOCK_SIDE_RAIN_PARTICLE_ID, BLOCK_SIDE_RAIN_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, CUSTOM_RAIN_SPLASH_PARTICLE_ID, CUSTOM_RAIN_SPLASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, RAIN_PUDDLE_PARTICLE_ID, RAIN_PUDDLE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BOAT_SPLASH_PARTICLE_ID, BOAT_SPLASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BOAT_TRAIL_FOAM_PARTICLE_ID, BOAT_TRAIL_FOAM_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BOAT_TRAIL_WAKE_PARTICLE_ID, BOAT_TRAIL_WAKE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, UNDERWATER_CHEST_BUBBLE_PARTICLE_ID, UNDERWATER_CHEST_BUBBLE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, UNDERWATER_ENDER_CHEST_BUBBLE_PARTICLE_ID, UNDERWATER_ENDER_CHEST_BUBBLE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TRAILER_SPLASH_OUTER_PARTICLE_ID, TRAILER_SPLASH_OUTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TRAILER_SPLASH_MIDDLE_PARTICLE_ID, TRAILER_SPLASH_MIDDLE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TRAILER_SPLASH_LOW_PARTICLE_ID, TRAILER_SPLASH_LOW_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TRAILER_SPLASH_BAND_PARTICLE_ID, TRAILER_SPLASH_BAND_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WATER_SPLASH_DROPLET_PARTICLE_ID, WATER_SPLASH_DROPLET_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WATER_CASCADE_PARTICLE_ID, WATER_CASCADE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WEATHER_PARTICLE_ID, WEATHER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, CAVE_DUST_PARTICLE_ID, CAVE_DUST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, AMETHYST_SPARKLE_PARTICLE_ID, AMETHYST_SPARKLE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LANTERN_MOTE_PARTICLE_ID, LANTERN_MOTE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, SOUL_LANTERN_MOTE_PARTICLE_ID, SOUL_LANTERN_MOTE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, COPPER_LANTERN_MOTE_PARTICLE_ID, COPPER_LANTERN_MOTE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TORCH_SPARK_PARTICLE_ID, TORCH_SPARK_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, SOUL_TORCH_SPARK_PARTICLE_ID, SOUL_TORCH_SPARK_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, COPPER_TORCH_SPARK_PARTICLE_ID, COPPER_TORCH_SPARK_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, TORCH_SMOKE_PARTICLE_ID, TORCH_SMOKE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, JELLYFISH_PARTICLE_ID, JELLYFISH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, END_PORTAL_EYE_PLACEMENT_PARTICLE_ID, END_PORTAL_EYE_PLACEMENT_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_LIGHT_RAY_PARTICLE_ID, WORLD_AMBIENCE_LIGHT_RAY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_DISTANT_LIGHT_RAY_PARTICLE_ID, WORLD_AMBIENCE_DISTANT_LIGHT_RAY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_LENS_FLARE_PARTICLE_ID, WORLD_AMBIENCE_LENS_FLARE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_WIND_GUST_PARTICLE_ID, WORLD_AMBIENCE_WIND_GUST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FIREFLY_PARTICLE_ID, WORLD_AMBIENCE_FIREFLY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_POLLEN_PARTICLE_ID, WORLD_AMBIENCE_POLLEN_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_WATER_POLLEN_PARTICLE_ID, WORLD_AMBIENCE_WATER_POLLEN_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_BIRD_PARTICLE_ID, WORLD_AMBIENCE_BIRD_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_BUTTERFLY_PARTICLE_ID, WORLD_AMBIENCE_BUTTERFLY_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_GOOSE_PARTICLE_ID, WORLD_AMBIENCE_GOOSE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_TUMBLEWEED_PARTICLE_ID, WORLD_AMBIENCE_TUMBLEWEED_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_CHERRY_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_CHERRY_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_PALE_OAK_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_PALE_OAK_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_SPRUCE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_SPRUCE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_BIRCH_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_BIRCH_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_JUNGLE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_JUNGLE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_ACACIA_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_ACACIA_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_MANGROVE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_MANGROVE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_PASSIVE_AZALEA_LEAF_PARTICLE_ID, WORLD_AMBIENCE_PASSIVE_AZALEA_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_LEAF_GUST_PARTICLE_ID, WORLD_AMBIENCE_LEAF_GUST_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_CHERRY_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_CHERRY_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_CHORUS_PETAL_PARTICLE_ID, WORLD_AMBIENCE_FALLING_CHORUS_PETAL_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_PALE_OAK_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_PALE_OAK_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_TINTED_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_TINTED_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_SPRUCE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_SPRUCE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_BIRCH_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_BIRCH_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_JUNGLE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_JUNGLE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_ACACIA_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_ACACIA_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_MANGROVE_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_MANGROVE_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_FALLING_AZALEA_LEAF_PARTICLE_ID, WORLD_AMBIENCE_FALLING_AZALEA_LEAF_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, WORLD_AMBIENCE_LEAF_WATER_SPLASH_PARTICLE_ID, WORLD_AMBIENCE_LEAF_WATER_SPLASH_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LEAF_LITTER_PARTICLE_ID, LEAF_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LEAF_LITTER_KICKUP_PARTICLE_ID, LEAF_LITTER_KICKUP_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, FLOWER_LITTER_PARTICLE_ID, FLOWER_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, PETAL_LITTER_PARTICLE_ID, PETAL_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BRANCH_LITTER_PARTICLE_ID, BRANCH_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, PEBBLE_LITTER_PARTICLE_ID, PEBBLE_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, BEACH_PEBBLE_LITTER_PARTICLE_ID, BEACH_PEBBLE_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, SHELL_LITTER_PARTICLE_ID, SHELL_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LILY_PAD_LITTER_PARTICLE_ID, LILY_PAD_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, LAVA_PLATE_PARTICLE_ID, LAVA_PLATE_PARTICLE);
      Registry.register(BuiltInRegistries.PARTICLE_TYPE, DUCKWEED_LITTER_PARTICLE_ID, DUCKWEED_LITTER_PARTICLE);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LEAF_LITTER_CONTACT_SOUND_ID, LEAF_LITTER_CONTACT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LEAF_LITTER_WALK_SOUND_ID, LEAF_LITTER_WALK_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LEAF_LITTER_RUSTLE_SOUND_ID, LEAF_LITTER_RUSTLE_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LEAF_LITTER_SLIDE_SOUND_ID, LEAF_LITTER_SLIDE_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LEAF_LITTER_LAND_SOUND_ID, LEAF_LITTER_LAND_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_HIT_01_SOUND_ID, TUMBLEWEED_HIT_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_HIT_02_SOUND_ID, TUMBLEWEED_HIT_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_HIT_03_SOUND_ID, TUMBLEWEED_HIT_03_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_HIT_04_SOUND_ID, TUMBLEWEED_HIT_04_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_PUNCH_01_SOUND_ID, TUMBLEWEED_PUNCH_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TUMBLEWEED_PUNCH_02_SOUND_ID, TUMBLEWEED_PUNCH_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_POP_01_SOUND_ID, LAVA_POP_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_POP_02_SOUND_ID, LAVA_POP_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_POP_03_SOUND_ID, LAVA_POP_03_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_SPRAY_01_SOUND_ID, LAVA_SPRAY_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_SPRAY_02_SOUND_ID, LAVA_SPRAY_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_DROPLET_01_SOUND_ID, LAVA_DROPLET_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, LAVA_DROPLET_02_SOUND_ID, LAVA_DROPLET_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, FALLING_LEAF_WATER_SOUND_ID, FALLING_LEAF_WATER_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, WATER_CASCADE_LOOP_SOUND_ID, WATER_CASCADE_LOOP_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BRANCH_LITTER_CONTACT_SOUND_ID, BRANCH_LITTER_CONTACT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, PEBBLE_LITTER_CONTACT_SOUND_ID, PEBBLE_LITTER_CONTACT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, WEATHER_DRIZZLE_SOUND_ID, WEATHER_DRIZZLE_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, WEATHER_LIGHT_RAIN_SOUND_ID, WEATHER_LIGHT_RAIN_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, WEATHER_DESERT_WIND_SOUND_ID, WEATHER_DESERT_WIND_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, WEATHER_NETHER_STORM_SOUND_ID, WEATHER_NETHER_STORM_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, PSYCHEDELIC_HALLUCINATION_SOUND_ID, PSYCHEDELIC_HALLUCINATION_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, FIREFLY_BUSH_AMBIENT_SOUND_ID, FIREFLY_BUSH_AMBIENT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, CICADA_AMBIENT_SOUND_ID, CICADA_AMBIENT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, DEEP_DARK_AMBIENT_SOUND_ID, DEEP_DARK_AMBIENT_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CONTINUOUS_SOUND_ID, BIRD_CONTINUOUS_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_01_SOUND_ID, BIRD_CALL_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_02_SOUND_ID, BIRD_CALL_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_03_SOUND_ID, BIRD_CALL_03_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_04_SOUND_ID, BIRD_CALL_04_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_05_SOUND_ID, BIRD_CALL_05_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_06_SOUND_ID, BIRD_CALL_06_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_CALL_07_SOUND_ID, BIRD_CALL_07_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, BIRD_FLYAWAY_SOUND_ID, BIRD_FLYAWAY_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, GEESE_CONTINUOUS_SOUND_ID, GEESE_CONTINUOUS_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, GEESE_FLOCK_CALL_01_SOUND_ID, GEESE_FLOCK_CALL_01_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, GEESE_FLOCK_CALL_02_SOUND_ID, GEESE_FLOCK_CALL_02_SOUND);
      Registry.register(BuiltInRegistries.SOUND_EVENT, GEESE_FLOCK_CALL_03_SOUND_ID, GEESE_FLOCK_CALL_03_SOUND);
   }

   static {
      LEAF_LITTER_CONTACT_SOUND = SoundEvent.createVariableRangeEvent(LEAF_LITTER_CONTACT_SOUND_ID);
      LEAF_LITTER_WALK_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_walk");
      LEAF_LITTER_WALK_SOUND = SoundEvent.createVariableRangeEvent(LEAF_LITTER_WALK_SOUND_ID);
      LEAF_LITTER_RUSTLE_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_rustle");
      LEAF_LITTER_RUSTLE_SOUND = SoundEvent.createVariableRangeEvent(LEAF_LITTER_RUSTLE_SOUND_ID);
      LEAF_LITTER_SLIDE_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_slide");
      LEAF_LITTER_SLIDE_SOUND = SoundEvent.createVariableRangeEvent(LEAF_LITTER_SLIDE_SOUND_ID);
      LEAF_LITTER_LAND_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "leaf_litter_land");
      LEAF_LITTER_LAND_SOUND = SoundEvent.createVariableRangeEvent(LEAF_LITTER_LAND_SOUND_ID);
      TUMBLEWEED_HIT_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_hit_01");
      TUMBLEWEED_HIT_01_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_HIT_01_SOUND_ID);
      TUMBLEWEED_HIT_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_hit_02");
      TUMBLEWEED_HIT_02_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_HIT_02_SOUND_ID);
      TUMBLEWEED_HIT_03_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_hit_03");
      TUMBLEWEED_HIT_03_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_HIT_03_SOUND_ID);
      TUMBLEWEED_HIT_04_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_hit_04");
      TUMBLEWEED_HIT_04_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_HIT_04_SOUND_ID);
      TUMBLEWEED_PUNCH_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_punch_01");
      TUMBLEWEED_PUNCH_01_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_PUNCH_01_SOUND_ID);
      TUMBLEWEED_PUNCH_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "tumbleweed_punch_02");
      TUMBLEWEED_PUNCH_02_SOUND = SoundEvent.createVariableRangeEvent(TUMBLEWEED_PUNCH_02_SOUND_ID);
      LAVA_POP_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_01");
      LAVA_POP_01_SOUND = SoundEvent.createVariableRangeEvent(LAVA_POP_01_SOUND_ID);
      LAVA_POP_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_02");
      LAVA_POP_02_SOUND = SoundEvent.createVariableRangeEvent(LAVA_POP_02_SOUND_ID);
      LAVA_POP_03_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_pop_03");
      LAVA_POP_03_SOUND = SoundEvent.createVariableRangeEvent(LAVA_POP_03_SOUND_ID);
      LAVA_SPRAY_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_spray_01");
      LAVA_SPRAY_01_SOUND = SoundEvent.createVariableRangeEvent(LAVA_SPRAY_01_SOUND_ID);
      LAVA_SPRAY_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_spray_02");
      LAVA_SPRAY_02_SOUND = SoundEvent.createVariableRangeEvent(LAVA_SPRAY_02_SOUND_ID);
      LAVA_DROPLET_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_droplet_01");
      LAVA_DROPLET_01_SOUND = SoundEvent.createVariableRangeEvent(LAVA_DROPLET_01_SOUND_ID);
      LAVA_DROPLET_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "lava_droplet_02");
      LAVA_DROPLET_02_SOUND = SoundEvent.createVariableRangeEvent(LAVA_DROPLET_02_SOUND_ID);
      FALLING_LEAF_WATER_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "falling_leaf_water");
      FALLING_LEAF_WATER_SOUND = SoundEvent.createVariableRangeEvent(FALLING_LEAF_WATER_SOUND_ID);
      WATER_CASCADE_LOOP_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "water_cascade_loop");
      WATER_CASCADE_LOOP_SOUND = SoundEvent.createVariableRangeEvent(WATER_CASCADE_LOOP_SOUND_ID);
      BRANCH_LITTER_CONTACT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "branch_litter_contact");
      BRANCH_LITTER_CONTACT_SOUND = SoundEvent.createVariableRangeEvent(BRANCH_LITTER_CONTACT_SOUND_ID);
      PEBBLE_LITTER_CONTACT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "pebble_litter_contact");
      PEBBLE_LITTER_CONTACT_SOUND = SoundEvent.createVariableRangeEvent(PEBBLE_LITTER_CONTACT_SOUND_ID);
      WEATHER_DRIZZLE_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "weather_drizzle");
      WEATHER_DRIZZLE_SOUND = SoundEvent.createVariableRangeEvent(WEATHER_DRIZZLE_SOUND_ID);
      WEATHER_LIGHT_RAIN_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "weather_light_rain");
      WEATHER_LIGHT_RAIN_SOUND = SoundEvent.createVariableRangeEvent(WEATHER_LIGHT_RAIN_SOUND_ID);
      WEATHER_DESERT_WIND_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "weather_desert_wind");
      WEATHER_DESERT_WIND_SOUND = SoundEvent.createVariableRangeEvent(WEATHER_DESERT_WIND_SOUND_ID);
      WEATHER_NETHER_STORM_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "weather_nether_storm");
      WEATHER_NETHER_STORM_SOUND = SoundEvent.createVariableRangeEvent(WEATHER_NETHER_STORM_SOUND_ID);
      PSYCHEDELIC_HALLUCINATION_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "psychedelic_hallucination");
      PSYCHEDELIC_HALLUCINATION_SOUND = SoundEvent.createVariableRangeEvent(PSYCHEDELIC_HALLUCINATION_SOUND_ID);
      FIREFLY_BUSH_AMBIENT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "firefly_bush_ambient");
      FIREFLY_BUSH_AMBIENT_SOUND = SoundEvent.createVariableRangeEvent(FIREFLY_BUSH_AMBIENT_SOUND_ID);
      CICADA_AMBIENT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "cicada_ambient");
      CICADA_AMBIENT_SOUND = SoundEvent.createVariableRangeEvent(CICADA_AMBIENT_SOUND_ID);
      DEEP_DARK_AMBIENT_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "deep_dark_ambient");
      DEEP_DARK_AMBIENT_SOUND = SoundEvent.createVariableRangeEvent(DEEP_DARK_AMBIENT_SOUND_ID);
      BIRD_CONTINUOUS_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_continuous");
      BIRD_CONTINUOUS_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CONTINUOUS_SOUND_ID, 128.0F);
      BIRD_CALL_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_01");
      BIRD_CALL_01_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_01_SOUND_ID, 128.0F);
      BIRD_CALL_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_02");
      BIRD_CALL_02_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_02_SOUND_ID, 128.0F);
      BIRD_CALL_03_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_03");
      BIRD_CALL_03_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_03_SOUND_ID, 128.0F);
      BIRD_CALL_04_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_04");
      BIRD_CALL_04_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_04_SOUND_ID, 128.0F);
      BIRD_CALL_05_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_05");
      BIRD_CALL_05_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_05_SOUND_ID, 128.0F);
      BIRD_CALL_06_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_06");
      BIRD_CALL_06_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_06_SOUND_ID, 128.0F);
      BIRD_CALL_07_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_call_07");
      BIRD_CALL_07_SOUND = SoundEvent.createFixedRangeEvent(BIRD_CALL_07_SOUND_ID, 128.0F);
      BIRD_FLYAWAY_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "bird_flyaway");
      BIRD_FLYAWAY_SOUND = SoundEvent.createFixedRangeEvent(BIRD_FLYAWAY_SOUND_ID, 128.0F);
      GEESE_CONTINUOUS_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "geese_continuous");
      GEESE_CONTINUOUS_SOUND = SoundEvent.createFixedRangeEvent(GEESE_CONTINUOUS_SOUND_ID, 256.0F);
      GEESE_FLOCK_CALL_01_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "geese_flock_call_01");
      GEESE_FLOCK_CALL_01_SOUND = SoundEvent.createFixedRangeEvent(GEESE_FLOCK_CALL_01_SOUND_ID, 256.0F);
      GEESE_FLOCK_CALL_02_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "geese_flock_call_02");
      GEESE_FLOCK_CALL_02_SOUND = SoundEvent.createFixedRangeEvent(GEESE_FLOCK_CALL_02_SOUND_ID, 256.0F);
      GEESE_FLOCK_CALL_03_SOUND_ID = Identifier.fromNamespaceAndPath("vybrantvisual", "geese_flock_call_03");
      GEESE_FLOCK_CALL_03_SOUND = SoundEvent.createFixedRangeEvent(GEESE_FLOCK_CALL_03_SOUND_ID, 256.0F);
   }
}
